#!/usr/bin/env python3
#
# https://www.raspberrypi.org/documentation/computers/os.html#vcgencmd

import subprocess
import json

def getinfo(cmd):
   result = subprocess.run(cmd.split(" "), capture_output=True)
   if (result.returncode != 0):
       print(f'Unable to get processes {result.stderr.decode("utf-8") }')
   
   return result.stdout.decode("utf-8")

data = [] 
result = getinfo("/sbin/zfs list -p -r -H -o name,available,usedbydataset,usedbysnapshots,usedbyrefreservation,refcompressratio,refreservation,refquota")
for line in result.splitlines():
   (name, avail, usedds, usedsnap, usedbyrefreservation, compress, reservation, quota) = line.split()
   if (quota == '-'):
      quota = 0
      data.append({ "name": name, "available": int(avail), "usedds": int(usedds), "usedsnapshot": int(usedsnap), "usedreservation": int(usedbyrefreservation), "compress": float(compress), "reservation": int(reservation), "quota": int(quota) })

print(json.dumps({"data": data}))
